# -*- coding: utf-8 -*-
"""clustering_and_fitting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mNSdqckOBirI9nnmki7NZAnwVcBJqDd3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("Cleaned_Students_Performance.csv")

# Check data
print(df.head())

# DATA CLEANING

# Check missing values
print(df.isnull().sum())

# Remove missing values (even if none exist)
df = df.dropna()

# Check data types
print(df.dtypes)

# Basic statistics
print(df.describe())

# RELATIONAL PLOT MATH SCIRE VS READING SCORE

plt.figure(figsize=(8,6))

sns.scatterplot(
    x='math_score',
        y='reading_score',
            data=df,
                color='royalblue',
                    s=50,
                        edgecolor='black',
                            alpha=0.7   # transparency for better visibility
                            )

plt.title("Relationship between Math and Reading Scores", fontsize=14, fontweight='bold')
plt.xlabel("Math Score", fontsize=12)
plt.ylabel("Reading Score", fontsize=12)

plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# RELATIONAL PLOT WRITING SCORE VS AVERAGE SCORE
# Shows strong relationship between writing score and overall average performance

plt.figure(figsize=(8,6))

sns.scatterplot(
    x='writing_score',
        y='average_score',
            data=df,
                color='green',
                    s=60,
                        edgecolor='black',
                            alpha=0.7
                            )

plt.title("Writing Score vs Average Score", fontsize=14)
plt.xlabel("Writing Score", fontsize=12)
plt.ylabel("Average Score", fontsize=12)
plt.grid(True)
plt.tight_layout()
plt.show()

# Convert 0/1 to labels
df['gender'] = df['gender'].map({0: 'Female', 1: 'Male'})

#CATEGORICAL PLOT
plt.figure(figsize=(8,6))

sns.countplot(
    x='gender',
        data=df,
            hue='gender',
                palette='Set2',
                    legend=False
                    )

plt.title("Distribution of Students by Gender", fontsize=14, fontweight='bold')
plt.xlabel("Gender", fontsize=12)
plt.ylabel("Count of Students", fontsize=12)

plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# ------------------------
# STATISTICAL PLOT (HEATMAP)
# ------------------------

plt.figure(figsize=(10,8))

sns.heatmap(
    df.corr(numeric_only=True),
        annot=True,          # shows values
            cmap='coolwarm',     # color style
                fmt=".2f",           # decimal format
                    linewidths=0.5
                    )

plt.title("Correlation Heatmap of Student Scores", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# STATISTICAL MOMENTS

# Mean: Average value of each numeric column
mean_values = df.mean(numeric_only=True)
print("Mean:\n", mean_values)

# Variance: Measures how spread out the data is from the mean
variance_values = df.var(numeric_only=True)
print("\nVariance:\n", variance_values)

# Skewness: Indicates the symmetry of the data distribution
skewness_values = df.skew(numeric_only=True)
print("\nSkewness:\n", skewness_values)

# Kurtosis: Measures the presence of outliers (tail heaviness)
kurtosis_values = df.kurtosis(numeric_only=True)
print("\nKurtosis:\n", kurtosis_values)

# SELECT FEATURES FOR CLUSTERING


X = df[['math_score', 'reading_score', 'writing_score', 'average_score']]


# SCALING DATA

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


# APPLY KMEANS CLUSTERING

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(X_scaled)

# Add cluster labels to dataset
df['Cluster'] = clusters


# CLUSTER VISUALIZATION


plt.figure(figsize=(8,6))

sns.scatterplot(
    x='math_score',
        y='reading_score',
            hue='Cluster',
                data=df,
                    palette='Set1',
                        s=60
                        )

plt.title("Clustering of Students based on Scores", fontsize=14, fontweight='bold')
plt.xlabel("Math Score")
plt.ylabel("Reading Score")
plt.grid(True)
plt.tight_layout()
plt.show()

# SELECT DATA FOR REGRESSION


X = df[['math_score']]   # independent variable
y = df['reading_score']  # dependent variable


# LINEAR REGRESSION MODEL

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X, y)


# PREDICTIONS

y_pred = model.predict(X)



# REGRESSION PLOT

plt.figure(figsize=(8,6))

# Actual data points
plt.scatter(X, y, color='blue', alpha=0.6, label='Actual Data')

# Fitted regression line
plt.plot(X, y_pred, color='red', linewidth=2, label='Fitted Line')

plt.title("Linear Regression: Math Score vs Reading Score", fontsize=14, fontweight='bold')
plt.xlabel("Math Score")
plt.ylabel("Reading Score")

plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()